@startuml

title __PRESENTER's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace presenter {
          abstract class com.hyphenate.easeui.modules.contact.presenter.EaseContactPresenter {
              + mView : IEaseContactListView
              {abstract} + addNote()
              + attachView()
              + detachView()
              {abstract} + loadData()
              + onDestroy()
              {abstract} + sortData()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace presenter {
          class com.hyphenate.easeui.modules.contact.presenter.EaseContactPresenterImpl {
              + addNote()
              + loadData()
              + sortData()
              - checkUserProvider()
              - sortList()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace presenter {
          interface com.hyphenate.easeui.modules.contact.presenter.IEaseContactListView {
              {abstract} + addNote()
              {abstract} + addNoteFail()
              {abstract} + loadContactListFail()
              {abstract} + loadContactListNoData()
              {abstract} + loadContactListSuccess()
              {abstract} + refreshList()
              {abstract} + refreshList()
              {abstract} + sortContactListSuccess()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
