@startuml

title __VIEWHOLDER's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseChatRowViewHolder {
          {static} - TAG : String
          - chatRow : EaseChatRow
          - context : Context
          - mItemClickListener : MessageListItemClickListener
          - message : EMMessage
          + EaseChatRowViewHolder()
          + getChatRow()
          + getContext()
          + initView()
          + onBubbleClick()
          + onDetachedFromWindow()
          + onResendClick()
          + setData()
          + setDataList()
          # handleReceiveMessage()
          # handleSendMessage()
          - handleMessage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseCustomViewHolder {
          + EaseCustomViewHolder()
          # handleReceiveMessage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseExpressionViewHolder {
          + EaseExpressionViewHolder()
          {static} + create()
          # handleReceiveMessage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseFileViewHolder {
          + EaseFileViewHolder()
          {static} + create()
          + onBubbleClick()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseImageViewHolder {
          + EaseImageViewHolder()
          {static} + create()
          + onBubbleClick()
          # handleReceiveMessage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseLocationViewHolder {
          + EaseLocationViewHolder()
          {static} + create()
          + onBubbleClick()
          # handleReceiveMessage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseTextViewHolder {
          + EaseTextViewHolder()
          {static} + create()
          + onBubbleClick()
          # handleReceiveMessage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseVideoViewHolder {
          {static} - TAG : String
          + EaseVideoViewHolder()
          {static} + create()
          + onBubbleClick()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace viewholder {
      class com.hyphenate.easeui.viewholder.EaseVoiceViewHolder {
          - voicePlayer : EaseChatRowVoicePlayer
          + EaseVoiceViewHolder()
          {static} + create()
          + onBubbleClick()
          + onDetachedFromWindow()
          - ackMessage()
          - asyncDownloadVoice()
          - play()
          - playVoice()
      }
    }
  }
  

  com.hyphenate.easeui.viewholder.EaseChatRowViewHolder .up.|> EaseChatRow.EaseChatRowActionCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
