@startuml

title __CONSTANTS's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace constants {
      interface com.hyphenate.easeui.constants.EaseConstant {
          {static} + CHATTYPE_CHATROOM : int
          {static} + CHATTYPE_GROUP : int
          {static} + CHATTYPE_SINGLE : int
          {static} + CONVERSATION_DELETE : String
          {static} + CONVERSATION_READ : String
          {static} + DEFAULT_SYSTEM_MESSAGE_ID : String
          {static} + DEFAULT_SYSTEM_MESSAGE_TYPE : String
          {static} + EXTRA_CHAT_TYPE : String
          {static} + EXTRA_CONVERSATION_ID : String
          {static} + EXTRA_IS_ROAM : String
          {static} + FORWARD_MSG_ID : String
          {static} + GROUP_LEAVE : String
          {static} + HISTORY_MSG_ID : String
          {static} + MESSAGE_ATTR_AT_MSG : String
          {static} + MESSAGE_ATTR_EXPRESSION_ID : String
          {static} + MESSAGE_ATTR_IS_BIG_EXPRESSION : String
          {static} + MESSAGE_ATTR_IS_VIDEO_CALL : String
          {static} + MESSAGE_ATTR_IS_VOICE_CALL : String
          {static} + MESSAGE_ATTR_VALUE_AT_MSG_ALL : String
          {static} + MESSAGE_CALL_SAVE : String
          {static} + MESSAGE_CHANGE_CHANGE : String
          {static} + MESSAGE_CHANGE_CMD_RECEIVE : String
          {static} + MESSAGE_CHANGE_DELETE : String
          {static} + MESSAGE_CHANGE_RECALL : String
          {static} + MESSAGE_CHANGE_RECEIVE : String
          {static} + MESSAGE_CHANGE_SEND_ERROR : String
          {static} + MESSAGE_CHANGE_SEND_PROGRESS : String
          {static} + MESSAGE_CHANGE_SEND_SUCCESS : String
          {static} + MESSAGE_FORWARD : String
          {static} + MESSAGE_TYPE_CMD : String
          {static} + MESSAGE_TYPE_CONFERENCE_INVITE : String
          {static} + MESSAGE_TYPE_EXPRESSION : String
          {static} + MESSAGE_TYPE_FILE : String
          {static} + MESSAGE_TYPE_IMAGE : String
          {static} + MESSAGE_TYPE_LIVE_INVITE : String
          {static} + MESSAGE_TYPE_LOCATION : String
          {static} + MESSAGE_TYPE_RECALL : String
          {static} + MESSAGE_TYPE_RECALLER : String
          {static} + MESSAGE_TYPE_TXT : String
          {static} + MESSAGE_TYPE_VIDEO : String
          {static} + MESSAGE_TYPE_VIDEO_CALL : String
          {static} + MESSAGE_TYPE_VOICE : String
          {static} + MESSAGE_TYPE_VOICE_CALL : String
          {static} + USER_CARD_EVENT : String
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
