@startuml

title __INTERFACES's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace interfaces {
          interface com.hyphenate.easeui.modules.contact.interfaces.IContactCustomListLayout {
              {abstract} + addCustomItem()
              {abstract} + addCustomItem()
              {abstract} + getCustomAdapter()
              {abstract} + setOnContactLoadListener()
              {abstract} + setOnCustomItemClickListener()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace interfaces {
          interface com.hyphenate.easeui.modules.contact.interfaces.IContactLayout {
              {abstract} + canUseRefresh()
              {abstract} + getContactList()
              {abstract} + getSwipeRefreshLayout()
              {abstract} + showNormal()
              {abstract} + showSimple()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace interfaces {
          interface com.hyphenate.easeui.modules.contact.interfaces.IContactListLayout {
              {abstract} + getItem()
              {abstract} + getListAdapter()
              {abstract} + setPresenter()
              {abstract} + showItemDefaultMenu()
              {abstract} + showItemHeader()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace interfaces {
          interface com.hyphenate.easeui.modules.contact.interfaces.IContactListStyle {
              {abstract} + setHeaderBackGround()
              {abstract} + setItemBackGround()
              {abstract} + setItemHeight()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace interfaces {
          interface com.hyphenate.easeui.modules.contact.interfaces.IContactTextStyle {
              {abstract} + setHeaderTextColor()
              {abstract} + setHeaderTextSize()
              {abstract} + setTitleTextColor()
              {abstract} + setTitleTextSize()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace interfaces {
          interface com.hyphenate.easeui.modules.contact.interfaces.OnContactLoadListener {
              + loadDataFail()
              {abstract} + loadDataFinish()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
