@startuml

title __INTERFACES's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace interfaces {
        interface com.hyphenate.easeui.modules.interfaces.IAvatarSet {
            {abstract} + setAvatarBorderColor()
            {abstract} + setAvatarBorderWidth()
            + setAvatarDefaultSrc()
            {abstract} + setAvatarRadius()
            {abstract} + setAvatarShapeType()
            {abstract} + setAvatarSize()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace interfaces {
        interface com.hyphenate.easeui.modules.interfaces.IPopupMenu {
            {abstract} + addItemMenu()
            {abstract} + clearMenu()
            {abstract} + findItemVisible()
            {abstract} + getMenuHelper()
            {abstract} + setOnPopupMenuDismissListener()
            {abstract} + setOnPopupMenuItemClickListener()
            {abstract} + setOnPopupMenuPreShowListener()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace interfaces {
        interface com.hyphenate.easeui.modules.interfaces.IPopupWindow {
            {abstract} + addItemMenu()
            {abstract} + addItemMenu()
            {abstract} + clearMenu()
            {abstract} + findItem()
            {abstract} + findItemVisible()
            {abstract} + getMenuHelper()
            {abstract} + setOnPopupWindowItemClickListener()
            {abstract} + showItemDefaultMenu()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace interfaces {
        interface com.hyphenate.easeui.modules.interfaces.IRecyclerView {
            {abstract} + addFooterAdapter()
            {abstract} + addHeaderAdapter()
            {abstract} + addRVItemDecoration()
            {abstract} + removeAdapter()
            {abstract} + removeRVItemDecoration()
            + setOnItemClickListener()
            + setOnItemLongClickListener()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
