@startuml

title __ADAPTER's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace adapter {
          class com.hyphenate.easeui.modules.contact.adapter.EaseContactCustomAdapter {
              - contactSetModel : EaseContactSetStyle
              + addItem()
              + addItem()
              + getViewHolder()
              + setSettingModel()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace adapter {
          class com.hyphenate.easeui.modules.contact.adapter.EaseContactCustomAdapter.CustomViewHolder {
              - clUser : ConstraintLayout
              - mAvatar : EaseImageView
              - mHeader : TextView
              - mName : TextView
              + CustomViewHolder()
              + initView()
              + setData()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace adapter {
          class com.hyphenate.easeui.modules.contact.adapter.EaseContactListAdapter {
              - contactSetModel : EaseContactSetStyle
              - emptyLayoutResource : int
              + getEmptyLayoutId()
              + getViewHolder()
              + setEmptyLayoutResource()
              + setSettingModel()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace adapter {
          class com.hyphenate.easeui.modules.contact.adapter.EaseContactListAdapter.ContactViewHolder {
              - clUser : ConstraintLayout
              - mAvatar : EaseImageView
              - mHeader : TextView
              - mName : TextView
              - mSignature : TextView
              - mUnreadMsgNumber : TextView
              + ContactViewHolder()
              + initView()
              + setData()
          }
        }
      }
    }
  }
  

  com.hyphenate.easeui.modules.contact.adapter.EaseContactCustomAdapter +-down- com.hyphenate.easeui.modules.contact.adapter.EaseContactCustomAdapter.CustomViewHolder
  com.hyphenate.easeui.modules.contact.adapter.EaseContactListAdapter +-down- com.hyphenate.easeui.modules.contact.adapter.EaseContactListAdapter.ContactViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
