@startuml

title __MODEL's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace model {
          class com.hyphenate.easeui.modules.contact.model.EaseContactCustomBean {
              - id : int
              - image : String
              - name : String
              - resourceId : int
              + getId()
              + getImage()
              + getName()
              + getResourceId()
              + setId()
              + setImage()
              + setName()
              + setResourceId()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace contact {
        namespace model {
          class com.hyphenate.easeui.modules.contact.model.EaseContactSetStyle {
              - avatarDefaultSrc : Drawable
              - headerBgDrawable : Drawable
              - headerTextColor : int
              - headerTextSize : float
              - showItemHeader : boolean
              - titleTextColor : int
              - titleTextSize : float
              + getAvatarDefaultSrc()
              + getHeaderBgDrawable()
              + getHeaderTextColor()
              + getHeaderTextSize()
              + getTitleTextColor()
              + getTitleTextSize()
              + isShowItemHeader()
              + setAvatarDefaultSrc()
              + setHeaderBgDrawable()
              + setHeaderTextColor()
              + setHeaderTextSize()
              + setShowItemHeader()
              + setTitleTextColor()
              + setTitleTextSize()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
