@startuml

title __DOMAIN's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace domain {
      class com.hyphenate.easeui.domain.EaseAvatarOptions {
          - avatarBorderColor : int
          - avatarBorderWidth : int
          - avatarRadius : int
          - avatarShape : int
          + getAvatarBorderColor()
          + getAvatarBorderWidth()
          + getAvatarRadius()
          + getAvatarShape()
          + setAvatarBorderColor()
          + setAvatarBorderWidth()
          + setAvatarRadius()
          + setAvatarShape()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace domain {
      class com.hyphenate.easeui.domain.EaseEmojicon {
          - bigIcon : int
          - bigIconPath : String
          - emojiText : String
          - icon : int
          - iconPath : String
          - identityCode : String
          - name : String
          + EaseEmojicon()
          + EaseEmojicon()
          + EaseEmojicon()
          + getBigIcon()
          + getBigIconPath()
          + getEmojiText()
          + getIcon()
          + getIconPath()
          + getIdentityCode()
          + getName()
          + getType()
          {static} + newEmojiText()
          + setBigIcon()
          + setBigIconPath()
          + setEmojiText()
          + setIcon()
          + setIconPath()
          + setIdentityCode()
          + setName()
          + setType()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace domain {
      enum Type {
        BIG_EXPRESSION
        NORMAL
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace domain {
      class com.hyphenate.easeui.domain.EaseEmojiconGroupEntity {
          - emojiconList : List<EaseEmojicon>
          - icon : int
          - name : String
          - type : Type
          + EaseEmojiconGroupEntity()
          + EaseEmojiconGroupEntity()
          + EaseEmojiconGroupEntity()
          + getEmojiconList()
          + getIcon()
          + getName()
          + getType()
          + setEmojiconList()
          + setIcon()
          + setName()
          + setType()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace domain {
      class com.hyphenate.easeui.domain.EaseUser {
          - avatar : String
          - birth : String
          - contact : int
          - email : String
          - ext : String
          - gender : int
          - initialLetter : String
          - lastModifyTimestamp : long
          - modifyInitialLetterTimestamp : long
          - nickname : String
          - phone : String
          - sign : String
          - username : String
          + EaseUser()
          + EaseUser()
          + getAvatar()
          + getBirth()
          + getContact()
          + getEmail()
          + getExt()
          + getGender()
          + getInitialLetter()
          + getInitialLetter()
          + getLastModifyTimestamp()
          + getModifyInitialLetterTimestamp()
          + getNickname()
          + getPhone()
          + getSign()
          + getUsername()
          {static} + parse()
          {static} + parse()
          {static} + parseUserInfo()
          + setAvatar()
          + setBirth()
          + setContact()
          + setEmail()
          + setExt()
          + setGender()
          + setInitialLetter()
          + setLastModifyTimestamp()
          + setModifyInitialLetterTimestamp()
          + setNickname()
          + setPhone()
          + setSign()
          + setUsername()
          + toString()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace domain {
      class com.hyphenate.easeui.domain.EaseUser.GetInitialLetter {
          - defaultLetter : String
          + getLetter()
      }
    }
  }
  

  com.hyphenate.easeui.domain.EaseEmojicon o-- com.hyphenate.easeui.domain.EaseEmojicon.Type : type
  com.hyphenate.easeui.domain.EaseEmojicon +-down- com.hyphenate.easeui.domain.EaseEmojicon.Type
  com.hyphenate.easeui.domain.EaseUser .up.|> Serializable
  com.hyphenate.easeui.domain.EaseUser +-down- com.hyphenate.easeui.domain.EaseUser.GetInitialLetter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
