@startuml

title __MODEL's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace chat {
        namespace model {
          class com.hyphenate.easeui.modules.chat.model.EaseChatItemStyleHelper {
              {static} - instance : EaseChatItemStyleHelper
              - style : EaseChatSetStyle
              + clear()
              {static} + getInstance()
              + getStyle()
              + setAvatarDefaultSrc()
              + setAvatarRadius()
              + setAvatarSize()
              + setBgDrawable()
              + setBorderColor()
              + setBorderWidth()
              + setItemHeight()
              + setItemMinHeight()
              + setItemShowType()
              + setReceiverBgDrawable()
              + setSenderBgDrawable()
              + setShapeType()
              + setShowAvatar()
              + setShowNickname()
              + setTextColor()
              + setTextSize()
              + setTimeBgDrawable()
              + setTimeTextColor()
              + setTimeTextSize()
              - EaseChatItemStyleHelper()
          }
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace modules {
      namespace chat {
        namespace model {
          class com.hyphenate.easeui.modules.chat.model.EaseChatSetStyle {
              - avatarDefaultSrc : Drawable
              - itemMinHeight : int
              - itemShowType : int
              - receiverBgDrawable : Drawable
              - senderBgDrawable : Drawable
              - showAvatar : boolean
              - showNickname : boolean
              - textColor : int
              - textSize : int
              - timeBgDrawable : Drawable
              - timeTextColor : int
              - timeTextSize : int
              + getAvatarDefaultSrc()
              + getItemMinHeight()
              + getItemShowType()
              + getReceiverBgDrawable()
              + getSenderBgDrawable()
              + getTextColor()
              + getTextSize()
              + getTimeBgDrawable()
              + getTimeTextColor()
              + getTimeTextSize()
              + isShowAvatar()
              + isShowNickname()
              + setAvatarDefaultSrc()
              + setItemMinHeight()
              + setItemShowType()
              + setReceiverBgDrawable()
              + setSenderBgDrawable()
              + setShowAvatar()
              + setShowNickname()
              + setTextColor()
              + setTextSize()
              + setTimeBgDrawable()
              + setTimeTextColor()
              + setTimeTextSize()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
