@startuml

title __DELEGATE's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.ConversationDelegate {
          + isForViewType()
          # createViewHolder()
          # getLayoutId()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.ConversationDelegate.ViewHolder {
          - avatar : EaseImageView
          - listIteaseLayout : ConstraintLayout
          - mContext : Context
          - mMsgState : ImageView
          - mUnreadMsgNumber : TextView
          - mentioned : TextView
          - message : TextView
          - name : TextView
          - time : TextView
          + ViewHolder()
          + initView()
          + setData()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseCustomAdapterDelegate {
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseExpressionAdapterDelegate {
          + EaseExpressionAdapterDelegate()
          + EaseExpressionAdapterDelegate()
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseFileAdapterDelegate {
          + EaseFileAdapterDelegate()
          + EaseFileAdapterDelegate()
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseImageAdapterDelegate {
          + EaseImageAdapterDelegate()
          + EaseImageAdapterDelegate()
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseLocationAdapterDelegate {
          + EaseLocationAdapterDelegate()
          + EaseLocationAdapterDelegate()
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      abstract class com.hyphenate.easeui.delegate.EaseMessageAdapterDelegate {
          - mItemClickListener : MessageListItemClickListener
          + EaseMessageAdapterDelegate()
          + EaseMessageAdapterDelegate()
          + EaseMessageAdapterDelegate()
          + createDefaultItemStyle()
          + onCreateViewHolder()
          + setListItemClickListener()
          {abstract} # createViewHolder()
          {abstract} # getEaseChatRow()
          - isSender()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseTextAdapterDelegate {
          + EaseTextAdapterDelegate()
          + EaseTextAdapterDelegate()
          + createViewHolder()
          + isForViewType()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseVideoAdapterDelegate {
          + EaseVideoAdapterDelegate()
          + EaseVideoAdapterDelegate()
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace delegate {
      class com.hyphenate.easeui.delegate.EaseVoiceAdapterDelegate {
          + EaseVoiceAdapterDelegate()
          + EaseVoiceAdapterDelegate()
          + isForViewType()
          # createViewHolder()
          # getEaseChatRow()
      }
    }
  }
  

  com.hyphenate.easeui.delegate.ConversationDelegate +-down- com.hyphenate.easeui.delegate.ConversationDelegate.ViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
