@startuml

title __UI's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseBaiduMapActivity {
          # address : String
          # latitude : double
          # longtitude : double
          - baiduMap : BaiduMap
          - lastLocation : BDLocation
          - mLocClient : LocationClient
          - mapView : MapView
          - titleBarMap : EaseTitleBar
          {static} + actionStart()
          {static} + actionStartForResult()
          {static} + actionStartForResult()
          + onBackPress()
          + onCreate()
          + onReceiveBDLocation()
          + onRightClick()
          # onDestroy()
          # onPause()
          # onResume()
          # showErrorToast()
          # showMap()
          # showMapWithLocationClient()
          - initData()
          - initIntent()
          - initListener()
          - initView()
          - sendLocation()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseBaiduMapActivity.BaiduSDKReceiver {
          + onReceive()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseBaiduMapActivity.EaseBDLocationListener {
          + onReceiveLocation()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseDingAckUserListActivity {
          {static} - TAG : String
          - ackUserListView : ListView
          - msg : EMMessage
          - titleBar : EaseTitleBar
          - tvNoData : TextView
          - userList : List<String>
          - userUpdateListener : IAckUserUpdateListener
          # onCreate()
          # onPause()
          # onResume()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseDingAckUserListActivity.AckUserAdapter {
          - context : Context
          - userList : List<String>
          + AckUserAdapter()
          + getCount()
          + getItem()
          + getItemId()
          + getView()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseDingAckUserListActivity.AckUserAdapter.ViewHolder {
          + nameView : TextView
          + ViewHolder()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseShowBigImageActivity {
          {static} - TAG : String
          - bitmap : Bitmap
          - default_res : int
          - filename : String
          - image : EasePhotoView
          - isDownloaded : boolean
          - pd : ProgressDialog
          + onBackPressed()
          # onCreate()
          - downloadImage()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseShowNormalFileActivity {
          {static} - TAG : String
          - progressBar : ProgressBar
          # onCreate()
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace ui {
      class com.hyphenate.easeui.ui.EaseShowVideoActivity {
          {static} - TAG : String
          - loadingLayout : RelativeLayout
          - localFilePath : Uri
          - progressBar : ProgressBar
          + onBackPressed()
          # onCreate()
          - downloadVideo()
          - showLocalVideo()
      }
    }
  }
  

  com.hyphenate.easeui.ui.EaseBaiduMapActivity .up.|> EaseTitleBar.OnBackPressListener
  com.hyphenate.easeui.ui.EaseBaiduMapActivity .up.|> EaseTitleBar.OnRightClickListener
  com.hyphenate.easeui.ui.EaseBaiduMapActivity o-- com.hyphenate.easeui.ui.EaseBaiduMapActivity.BaiduSDKReceiver : mBaiduReceiver
  com.hyphenate.easeui.ui.EaseBaiduMapActivity +-down- com.hyphenate.easeui.ui.EaseBaiduMapActivity.BaiduSDKReceiver
  com.hyphenate.easeui.ui.EaseBaiduMapActivity +-down- com.hyphenate.easeui.ui.EaseBaiduMapActivity.EaseBDLocationListener
  com.hyphenate.easeui.ui.EaseBaiduMapActivity.EaseBDLocationListener .up.|> BDLocationListener
  com.hyphenate.easeui.ui.EaseDingAckUserListActivity o-- com.hyphenate.easeui.ui.EaseDingAckUserListActivity.AckUserAdapter : userAdapter
  com.hyphenate.easeui.ui.EaseDingAckUserListActivity +-down- com.hyphenate.easeui.ui.EaseDingAckUserListActivity.AckUserAdapter
  com.hyphenate.easeui.ui.EaseDingAckUserListActivity.AckUserAdapter +-down- com.hyphenate.easeui.ui.EaseDingAckUserListActivity.AckUserAdapter.ViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
