@startuml

title __EMOJICON's Class Diagram__\n

  namespace com.hyphenate.easeui {
    namespace widget {
      namespace emojicon {
        class com.hyphenate.easeui.widget.emojicon.EaseEmojiconIndicatorView {
            - context : Context
            - dotHeight : int
            - dotViews : List<ImageView>
            - selectedBitmap : Bitmap
            - unselectedBitmap : Bitmap
            + EaseEmojiconIndicatorView()
            + EaseEmojiconIndicatorView()
            + EaseEmojiconIndicatorView()
            + init()
            + selectTo()
            + selectTo()
            + updateIndicator()
            # onDetachedFromWindow()
            - init()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace widget {
      namespace emojicon {
        class com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView {
            - bigEmojiconColumns : int
            - bigEmojiconRows : int
            - context : Context
            - emojiconColumns : int
            - emojiconRows : int
            - firstGroupPageSize : int
            - groupEntities : List<EaseEmojiconGroupEntity>
            - maxPageCount : int
            - pagerAdapter : PagerAdapter
            - previousPagerPosition : int
            - viewpages : List<View>
            + EaseEmojiconPagerView()
            + EaseEmojiconPagerView()
            + addEmojiconGroup()
            + getGroupGridViews()
            + init()
            + removeEmojiconGroup()
            + setGroupPostion()
            + setPagerViewListener()
            - getPageSize()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace widget {
      namespace emojicon {
        interface com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView.EaseEmojiconPagerViewListener {
            {abstract} + onDeleteImageClicked()
            {abstract} + onExpressionClicked()
            {abstract} + onGroupInnerPagePostionChanged()
            {abstract} + onGroupMaxPageSizeChanged()
            {abstract} + onGroupPagePostionChangedTo()
            {abstract} + onGroupPositionChanged()
            {abstract} + onPagerViewInited()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace widget {
      namespace emojicon {
        class com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView.EmojiPagerChangeListener {
            + onPageScrollStateChanged()
            + onPageScrolled()
            + onPageSelected()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace widget {
      namespace emojicon {
        class com.hyphenate.easeui.widget.emojicon.EaseEmojiconScrollTabBar {
            - context : Context
            - scrollView : HorizontalScrollView
            - tabContainer : LinearLayout
            - tabList : List<ImageView>
            + EaseEmojiconScrollTabBar()
            + EaseEmojiconScrollTabBar()
            + EaseEmojiconScrollTabBar()
            + addTab()
            + removeTab()
            + selectedTo()
            + setTabBarItemClickListener()
            - init()
            - scrollTo()
        }
      }
    }
  }
  

  namespace com.hyphenate.easeui {
    namespace widget {
      namespace emojicon {
        interface com.hyphenate.easeui.widget.emojicon.EaseEmojiconScrollTabBar.EaseScrollTabBarItemClickListener {
            {abstract} + onItemClick()
        }
      }
    }
  }
  

  com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView o-- com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView.EaseEmojiconPagerViewListener : pagerViewListener
  com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView +-down- com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView.EaseEmojiconPagerViewListener
  com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView +-down- com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView.EmojiPagerChangeListener
  com.hyphenate.easeui.widget.emojicon.EaseEmojiconPagerView.EmojiPagerChangeListener .up.|> OnPageChangeListener
  com.hyphenate.easeui.widget.emojicon.EaseEmojiconScrollTabBar o-- com.hyphenate.easeui.widget.emojicon.EaseEmojiconScrollTabBar.EaseScrollTabBarItemClickListener : itemClickListener
  com.hyphenate.easeui.widget.emojicon.EaseEmojiconScrollTabBar +-down- com.hyphenate.easeui.widget.emojicon.EaseEmojiconScrollTabBar.EaseScrollTabBarItemClickListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
